Mobile home page changes
mlcsu-digital-innovations/FindMeAS12Doctor pull request #351
Opened 2020-08-24 11:29 UTC by stephenharland

2020-08-24 12:40 UTC, MarkC33 commented on Fmas12d.Mobile/src/app/pages/home/home.page.html
> +          <h3>You have not registed any avaliability.</h3>
Spelling :-)

2020-08-24 12:42 UTC, MarkC33 requested changes
Spelling mistakes to be corrected

2020-08-24 13:12 UTC, stephenharland commented on Fmas12d.Mobile/src/app/pages/home/home.page.html
> +          <h3>You have not registed any avaliability.</h3>
I can only see 1, is that right?

2020-09-15 08:37 UTC, MarkC33 approved these changes

2020-09-15 08:37 UTC, merged